project:
  type: website
  output-dir: docs

website:
  title: "Hawkinslab"
  navbar:
    left:
      - href: index.qmd
        text: Home

      - text: Research
        menu:
          - text: "Projects"
            href:  research/projects/projects.qmd
          - text: "Team"
            href: research/team/researchTeam.qmd
          - text: "Publications"
            href: research/publication/publication.qmd
      - text: "Teaching"
        menu:
          - text: "CIVE461/861"
            href: teaching/CIVE461/index.qmd
          - text: "CIVE864"
            href: teaching/CIVE864/index.qmd 
    background: "#d00000"
    
  sidebar:
    - id: default
      title: "Default"
      background: "#f5f1e7"  
      style: "docked"
      search: true
      align: center
      contents:
        - section: "Home"
          contents:
            - href: index.qmd
              text: Home

    - id: CIVE461
      title: "CIVE 461"
      background: "#f5f1e7"
      logo: "assets/images/teaching/cive_461_logo.png"
      style: "docked"
      search: true
      align: center
      contents:
        - section: "Administration"
          contents:
            - href: teaching/CIVE461/course-overview.qmd
              text: Overview
            - href: teaching/CIVE461/course-syllabus.qmd
              text: Syllabus
            - href: teaching/CIVE461/team.qmd
              text: "Teaching team"
            - href: teaching/CIVE461/index.qmd
              text: Schedule
            - href: teaching/CIVE461/course-links.qmd
              text: Useful links
            - href: teaching/CIVE461/course-faq.qmd
              text: FAQ
        - section: "Computing"
          contents:
            - href: teaching/CIVE461/computing/computing-access.qmd
              text: "Access"
            - href: teaching/CIVE461/computing/computing-troubleshooting.qmd
              text: "Troubleshooting"
        - section: "Weekly Materials"
          contents:
            - href: teaching/CIVE461/weeks/week-1.qmd
              text: "Week 1"
            - href: teaching/CIVE461/weeks/week-2.qmd
              text: "Week 2"
        - section: "Project"
          contents:
            - href: teaching/CIVE461/project/project-description.qmd
              text: "Description"
            - href: teaching/CIVE461/project/project-tips-resources.qmd
              text: "Tips + resources"

    - id: CIVE864
      title: "CIVE 864"
      background: "#f5f1e7"
      logo: "assets/images/teaching/cive864_logo.png"
      style: "docked"
      search: true
      align: center
      contents:
        - section: "Administration"
          contents:
            - href: teaching/CIVE864/course-overview.qmd
              text: Overview
            - href: teaching/CIVE864/course-syllabus.qmd
              text: Syllabus
            - href: teaching/CIVE864/course-support.qmd
              text: Support
            - href: teaching/CIVE864/team.qmd
              text: "Teaching team"
            - href: teaching/CIVE864/index.qmd
              text: Schedule
            - href: teaching/CIVE864/course-links.qmd
              text: Useful links
            - href: teaching/CIVE864/course-faq.qmd
              text: FAQ

        - section: "Weekly Materials"
          contents:
            - href: teaching/CIVE864/weeks/week-1.qmd
              text: "Week 1"
            - href: teaching/CIVE864/weeks/week-2.qmd
              text: "Week 2"

        - section: "Supplemental Notes"
          contents:
            - href: teaching/CIVE864/supplemental/slr-derivations.qmd
              text: SLR derivations

    - id: Project
      style: "docked"
      search: true
      align: center
      contents:
        - href: research/projects/projects.qmd
          text: Research
        - section: "EV"
          contents:
            - href: research/projects/ev.qmd
              text: EV Adoption Graphs

    - id: Teaching
      style: "docked"
      search: true
      align: center
      contents:
        - section: "Teaching"
          contents:
            - href: teaching/CIVE461/CIVE461.qmd
              text: CIVE461
            - href: teaching/CIVE864/CIVE864.qmd
              text: CIVE864

  page-footer:
    left: |
      Developed by Hawkinslab
    center:
      - text: "About"
        href: about.qmd
      # - text: "FAQ"
      #   href: docs/faq/index.qmd
      # - text: "License"
      #   href: license.qmd
      # - text: "Trademark"
      #   href: trademark.qmd
      
    right:
      - icon: github
        href: https://github.com/UNL-Hawkins-Lab/Hawkinslab
        aria-label: Quarto GitHub     
    background: "#f5f1e7"
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



