project:
  type: website
  output-dir: docs

website:
  title: "Hawkinslab"
  navbar:
      # home, research, and teaching
    left:
      - href: index.qmd
        text: Home

      - text: Research
        menu:
          - text: "Projects"
            href:  research/projects.qmd
          - text: "Team"
            href: research/team/research-team.qmd
          - text: "Publications"
            href: research/publication/publication.qmd
      - text: "Teaching"
        menu:
          - text: "CIVE461/861"
            href: teaching/CIVE461.qmd
          - text: "CIVE864"
            href: teaching/CIVE864.qmd 

  sidebar:
    - id: CIVE461
      title: "CIVE461"

      style: "docked"
      search: true
      align: center
      contents:
        - section: "Administration"
          contents:
            - href: course-overview.qmd
              text: Overview
            - href: course-syllabus.qmd
              text: Syllabus
            - href: course-support.qmd
              text: Support
            - href: team.qmd
              text: "Teaching team"
            - href: index.qmd
              text: Schedule
            - href: course-links.qmd
              text: Useful links
            - href: course-faq.qmd
              text: FAQ

        - section: "Computing Access"
          contents:
            - href: project-description.qmd
              text: Description
            - href: project-tips-resources.qmd
              text: Tips + resources

        - section: "Weekly Materials"
          contents:
            - href: weeks/week-1.qmd
              text: "Week 1"
            - href: weeks/week-2.qmd
              text: "Week 2"

        - section: "Supplemental Notes"
          contents:
            - href: supplemental/slr-derivations.qmd
              text: SLR derivations
            - href: supplemental/model-diagnostics-matrix.qmd
              text: Model diagnostics
            - href: supplemental/mlr-matrix.qmd
              text: MLR matrix notation
            - href: supplemental/log-transformations.qmd
              text: Log transformations
            - href: supplemental/model-selection-criteria.qmd
              text: Model selection criteria

    - id: CIVE864
      style: "docked"
      search: true
      align: center
      contents:
        - section: "Administration"
          contents:
            - href: course-overview.qmd
              text: Overview
            - href: course-syllabus.qmd
              text: Syllabus
            - href: course-support.qmd
              text: Support
            - href: team.qmd
              text: "Teaching team"
            - href: index.qmd
              text: Schedule
            - href: course-links.qmd
              text: Useful links
            - href: course-faq.qmd
              text: FAQ

        - section: "Computing Access"
          contents:
            - href: project-description.qmd
              text: Description
            - href: project-tips-resources.qmd
              text: Tips + resources

        - section: "Weekly Materials"
          contents:
            - href: weeks/week-1.qmd
              text: "Week 1"
            - href: weeks/week-2.qmd
              text: "Week 2"

        - section: "Supplemental Notes"
          contents:
            - href: supplemental/slr-derivations.qmd
              text: SLR derivations

    - id: Publication
      style: "docked"
      search: true
      align: center
      contents:
        - section: "EV"
          contents:
            - href: research/publication/ev.qmd
              text: EV Adoption Graphs
       

  


        


  page-footer:
    left: |
      Developed by Hawkinslab
    center:
      - text: "About"
        href: about.qmd
      # - text: "FAQ"
      #   href: docs/faq/index.qmd
      # - text: "License"
      #   href: license.qmd
      # - text: "Trademark"
      #   href: trademark.qmd
      
    right:
      - icon: github
        href: https://github.com/UNL-Hawkins-Lab/Hawkinslab
        aria-label: Quarto GitHub     

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



